# Generated by Django 3.0.8 on 2021-10-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='productoexistencia',
            field=models.IntegerField(),
        ),
    ]
