# Generated by Django 3.0.8 on 2021-10-06 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20211005_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='productogrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productogrupo_p', to='inventario.grupo'),
        ),
    ]
